### ISSUE TITLE
signPKCS7  invalid client_secret or I do not correct message

### ISSUE THREAD

**Issue by evstafiy** [fr05t1k/esia#1]
------E9FBCD085F9A40FCCC47C3148AE2BE4EContent-Type:%20application_pkcs7-signature;%20name=%22smime.p7s%22Content-Transfer-Encoding:%20base64Content-Disposition:%20attachment;%20filename=%22smime.p7s%22

**Comment by fr05t1k** [comment]
Опишите подробнее проблему.

**Comment by evstafiy** [comment]
Станислав, здравствуйте. Вы моя последняя надежда! Быть может я не правильно генерю сертификат. Делаю я через openssl
В прикрепленном файле содержимое сертификата.
В строке 

$sign = str_replace("\n", "", $this->urlSafe($signed[3]));

он берет вот эту часть сертификата, но даже если я беру $signed[3] и преобразую ее все равно подпись не верная.

------29D16A255291301940E6EB0F1F315703
Content-Type: application/pkcs7-signature; name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"

Помогите, пожалуйста, тех. поддержка толком не отвечает, примеров нет, единственная отличная и понятная реализация это у вам, за что вам огромное спасибо!



>Пятница, 25 декабря 2015, 2:49 -08:00 от Stanislav <notifications@github.com>:
>
>Опишите подробнее проблему. 
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Александр Нестеров
nesterov_ao42@mail.ru

MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg="sha1"; boundary="----29D16A255291301940E6EB0F1F315703"

This is an S/MIME signed message

------29D16A255291301940E6EB0F1F315703

------29D16A255291301940E6EB0F1F315703
Content-Type: application/pkcs7-signature; name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"

MIIG1wYJKoZIhvcNAQcCoIIGyDCCBsQCAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3
DQEHAaCCBCYwggQiMIIDCqADAgECAgkAzR14Ah0Jt9gwDQYJKoZIhvcNAQELBQAw
gY8xCzAJBgNVBAYTAlJVMREwDwYDVQQIDAhLZW1lcm92bzERMA8GA1UEBwwIS2Vt
ZXJvdm8xFzAVBgNVBAoMDmFzay1nbG9uYXNzLnJ1MQwwCgYDVQQLDANhc2sxDDAK
BgNVBAMMA2FzazElMCMGCSqGSIb3DQEJARYWc3VwcG9ydEBhc2stZ2xvbmFzcy5y
dTAeFw0xNTEyMjUwMjIwMDZaFw0yNTEyMjIwMjIwMDZaMIGPMQswCQYDVQQGEwJS
VTERMA8GA1UECAwIS2VtZXJvdm8xETAPBgNVBAcMCEtlbWVyb3ZvMRcwFQYDVQQK
DA5hc2stZ2xvbmFzcy5ydTEMMAoGA1UECwwDYXNrMQwwCgYDVQQDDANhc2sxJTAj
BgkqhkiG9w0BCQEWFnN1cHBvcnRAYXNrLWdsb25hc3MucnUwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDCL2ebDmAo8VN6iYOva7RCCrLCXbB9ZAN5VZpW
SJYqmH4fFtF2xXbqy0yoRFQu7KWvv9/YRvett2JuzM0uit9m5F4C+mmIA8Ws8jzU
jdmKdFy+Im3U1cuq9B26qt06yf6CivjDnrFa0QPHSAN0SDbT2oMkIohs5m5KYn07
8XdoGt0ct6Ew9cjXKo3g1botYDeL+TqVyCItr5IdOGAK37dRPpCvrVkfuCHbLf+W
CF+O/CGYnjbZVY4iMfSAsyioVuwrgWK7Xn6Pf6KigxodQXloWgxuRWM3mUknM65H
Xk9ZWHG4bfzmWGbvsa0vF56k6WSPsISc7qfKAPD/bATx/QpFAgMBAAGjfzB9MB0G
A1UdDgQWBBSSKzEUt3E4Gja3QrggHhzSxDC/LjAOBgNVHQ8BAf8EBAMCBPAwHQYD
VR0lBBYwFAYIKwYBBQUHAwQGCCsGAQUFBwMCMB8GA1UdIwQYMBaAFJIrMRS3cTga
NrdCuCAeHNLEML8uMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAFTF
NAJF5kP9UiBr9cUhB+yE0/kA7Zx7YCEly0tT2lD+lh5KoA8evdGOyL5vBZJ3jH9x
wAFD/pY7K9inNLqEfunAVjbpS3Y2e3Z+gtEe+hJTrWjOIc2UK1jAg/X+O+uVIFLG
cTOI08ZG1t3nmXq3RgrcSvUD3gDi5I7xEFrwgknjB/ngtDNxYMeGolXBzIL/mFPW
HA+Vz4P7gSydKHQieDVS3QfSLFkh0HnAnXBx+9AuDVpdQwXDpmEwXM2wDVX0ssmc
L2CbKY9zSGJrT9ne56g4wdYZgXNpw4/Ccxp8hgsRWJ3lsMU0jJL+1NuOYCEy+G+e
ZSn70oHpuJfwBMAi1CcxggJ5MIICdQIBATCBnTCBjzELMAkGA1UEBhMCUlUxETAP
BgNVBAgMCEtlbWVyb3ZvMREwDwYDVQQHDAhLZW1lcm92bzEXMBUGA1UECgwOYXNr
LWdsb25hc3MucnUxDDAKBgNVBAsMA2FzazEMMAoGA1UEAwwDYXNrMSUwIwYJKoZI
hvcNAQkBFhZzdXBwb3J0QGFzay1nbG9uYXNzLnJ1AgkAzR14Ah0Jt9gwCQYFKw4D
AhoFAKCBsTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEP
Fw0xNTEyMjUxMzE4MzNaMCMGCSqGSIb3DQEJBDEWBBTaOaPuXmtLDTJVv++VYBiQ
r9gHCTBSBgkqhkiG9w0BCQ8xRTBDMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIA
gDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDANBgkqhkiG
9w0BAQEFAASCAQBuv9qVd9Z0pfWHvnprKud6eJQYwbH2W3/v/sDKOGEan5xRc57w
/H5h29vArCHANDgQrdDrvlCE3HqqDn0hUXUaPqeOMkmmb4KywfVp3Uq4XMiUEn8s
DXPd8o98eoBgZG2cSqCcp/6xsy7uN3Ne/2y0QJYELdD77n2yfMq6XJGivZU9QfS0
XL36imz9dYFDVMZR4ILKYDSuhYLnb/VRl5ipAPK1qoqOROuWS1Bl/4wq+LXmV7zC
dUeT2Vboe8e/czraSWd8c1ra2GqT6OQgW6ZP2Fvd3urCmUvYZx/sExWcjuMuHNp2
GGBDfbLsW1EGKn0H8W/xNjQeXlMlOorCBKCT

------29D16A255291301940E6EB0F1F315703--

**Comment by fr05t1k** [comment]
А какое сообщение получилось в $signFile?

**Comment by fr05t1k** [comment]
Вот кстати пример генерации ключа и сертификата 
```
keytool -genkey -storepass 123456 -keypass 123456 -keyalg RSA -alias test -validity 3600 -keystore keystore.jks

keytool -v -exportcert -alias test -keystore keystore.jks -rfc -file sert.crt # это будет сертификат

keytool -v -importkeystore -srckeystore keystore.jks -srcalias test -destkeystore keystore.p12 -deststoretype PKCS12

openssl pkcs12 -in keystore.p12  -nocerts -out private.key # это будет приватный ключ
```

**Comment by fr05t1k** [comment]
Должен брать вот эту часть 

```
MIIG1wYJKoZIhvcNAQcCoIIGyDCCBsQCAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3
DQEHAaCCBCYwggQiMIIDCqADAgECAgkAzR14Ah0Jt9gwDQYJKoZIhvcNAQELBQAw
gY8xCzAJBgNVBAYTAlJVMREwDwYDVQQIDAhLZW1lcm92bzERMA8GA1UEBwwIS2Vt
ZXJvdm8xFzAVBgNVBAoMDmFzay1nbG9uYXNzLnJ1MQwwCgYDVQQLDANhc2sxDDAK
BgNVBAMMA2FzazElMCMGCSqGSIb3DQEJARYWc3VwcG9ydEBhc2stZ2xvbmFzcy5y
dTAeFw0xNTEyMjUwMjIwMDZaFw0yNTEyMjIwMjIwMDZaMIGPMQswCQYDVQQGEwJS
VTERMA8GA1UECAwIS2VtZXJvdm8xETAPBgNVBAcMCEtlbWVyb3ZvMRcwFQYDVQQK
DA5hc2stZ2xvbmFzcy5ydTEMMAoGA1UECwwDYXNrMQwwCgYDVQQDDANhc2sxJTAj
BgkqhkiG9w0BCQEWFnN1cHBvcnRAYXNrLWdsb25hc3MucnUwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDCL2ebDmAo8VN6iYOva7RCCrLCXbB9ZAN5VZpW
SJYqmH4fFtF2xXbqy0yoRFQu7KWvv9/YRvett2JuzM0uit9m5F4C+mmIA8Ws8jzU
jdmKdFy+Im3U1cuq9B26qt06yf6CivjDnrFa0QPHSAN0SDbT2oMkIohs5m5KYn07
8XdoGt0ct6Ew9cjXKo3g1botYDeL+TqVyCItr5IdOGAK37dRPpCvrVkfuCHbLf+W
CF+O/CGYnjbZVY4iMfSAsyioVuwrgWK7Xn6Pf6KigxodQXloWgxuRWM3mUknM65H
Xk9ZWHG4bfzmWGbvsa0vF56k6WSPsISc7qfKAPD/bATx/QpFAgMBAAGjfzB9MB0G
A1UdDgQWBBSSKzEUt3E4Gja3QrggHhzSxDC/LjAOBgNVHQ8BAf8EBAMCBPAwHQYD
VR0lBBYwFAYIKwYBBQUHAwQGCCsGAQUFBwMCMB8GA1UdIwQYMBaAFJIrMRS3cTga
NrdCuCAeHNLEML8uMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAFTF
NAJF5kP9UiBr9cUhB+yE0/kA7Zx7YCEly0tT2lD+lh5KoA8evdGOyL5vBZJ3jH9x
wAFD/pY7K9inNLqEfunAVjbpS3Y2e3Z+gtEe+hJTrWjOIc2UK1jAg/X+O+uVIFLG
cTOI08ZG1t3nmXq3RgrcSvUD3gDi5I7xEFrwgknjB/ngtDNxYMeGolXBzIL/mFPW
HA+Vz4P7gSydKHQieDVS3QfSLFkh0HnAnXBx+9AuDVpdQwXDpmEwXM2wDVX0ssmc
L2CbKY9zSGJrT9ne56g4wdYZgXNpw4/Ccxp8hgsRWJ3lsMU0jJL+1NuOYCEy+G+e
ZSn70oHpuJfwBMAi1CcxggJ5MIICdQIBATCBnTCBjzELMAkGA1UEBhMCUlUxETAP
BgNVBAgMCEtlbWVyb3ZvMREwDwYDVQQHDAhLZW1lcm92bzEXMBUGA1UECgwOYXNr
LWdsb25hc3MucnUxDDAKBgNVBAsMA2FzazEMMAoGA1UEAwwDYXNrMSUwIwYJKoZI
hvcNAQkBFhZzdXBwb3J0QGFzay1nbG9uYXNzLnJ1AgkAzR14Ah0Jt9gwCQYFKw4D
AhoFAKCBsTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEP
Fw0xNTEyMjUxMzE4MzNaMCMGCSqGSIb3DQEJBDEWBBTaOaPuXmtLDTJVv++VYBiQ
r9gHCTBSBgkqhkiG9w0BCQ8xRTBDMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIA
gDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDANBgkqhkiG
9w0BAQEFAASCAQBuv9qVd9Z0pfWHvnprKud6eJQYwbH2W3/v/sDKOGEan5xRc57w
/H5h29vArCHANDgQrdDrvlCE3HqqDn0hUXUaPqeOMkmmb4KywfVp3Uq4XMiUEn8s
DXPd8o98eoBgZG2cSqCcp/6xsy7uN3Ne/2y0QJYELdD77n2yfMq6XJGivZU9QfS0
XL36imz9dYFDVMZR4ILKYDSuhYLnb/VRl5ipAPK1qoqOROuWS1Bl/4wq+LXmV7zC
dUeT2Vboe8e/czraSWd8c1ra2GqT6OQgW6ZP2Fvd3urCmUvYZx/sExWcjuMuHNp2
GGBDfbLsW1EGKn0H8W/xNjQeXlMlOorCBKCT
```

**Comment by fr05t1k** [comment]
Вот пример сообщения

```
Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="----CCC81977A319A32815270F41E73EFFD9"

This is an S/MIME signed message

------CCC81977A319A32815270F41E73EFFD9
http://esia.gosuslugi.ru/usr_inf2015.12.25 15:07:23 +0000INSP03211cae799b1-3ade-40fa-9029-1d9056a8f9db
------CCC81977A319A32815270F41E73EFFD9
Content-Type: application/x-pkcs7-signature; name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"

MIIEJAYJKoZIhvcNAQcCoIIEFTCCBBECAQExDzANBglghkgBZQMEAgEFADALBgkq
hkiG9w0BBwGgggIFMIICATCCAWoCCQDuV6K/drn++DANBgkqhkiG9w0BAQUFADBF
MQswCQYDVQQGEwJSVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMB4XDTE1MTAwNjA1MjQwM1oXDTI1MTAwMzA1
MjQwM1owRTELMAkGA1UEBhMCUlUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNV
BAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCBnzANBgkqhkiG9w0BAQEFAAOB
jQAwgYkCgYEAwKEWMoa/dyEGJ1OI8M07lP0r6R6Js05RoarMKJpVRbkmiO9byqcb
CEiPJLZfdcNsORGZc9L09YBbUjJkpy4TY+qzNOpQMoScfeHA/5LzlXqzOdDapYUu
XkxHQmOfAHBR3anyUuVuCBJABp0jxxMVTXxKtxgpfqLH2Jmr31yu6vMCAwEAATAN
BgkqhkiG9w0BAQUFAAOBgQCJwsCDtw4IoPQiVw1fpEc8aS/QlujwChvyaTJUJ96c
WHQs5hz7M23rPTibTZ4ooJ6jbP/e7vaxpXpXShNBnnP3RVCOKX0P0t1XS1nCvr65
1KXlIwNWTXZxSZ72vl5ySU71uOSaVPjicxIaPG93IFe5X7VTV4QDanSZqQqLwZsU
GTGCAeMwggHfAgEBMFIwRTELMAkGA1UEBhMCUlUxEzARBgNVBAgTClNvbWUtU3Rh
dGUxITAfBgNVBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZAIJAO5Xor92uf74
MA0GCWCGSAFlAwQCAQUAoIHkMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJ
KoZIhvcNAQkFMQ8XDTE1MTIyNTE1MDcyM1owLwYJKoZIhvcNAQkEMSIEIJ2c7Ku3
aj2pIKzZ9hVoi7/mE9l0rfclMR7+hXPPq9KXMHkGCSqGSIb3DQEJDzFsMGowCwYJ
YIZIAWUDBAEqMAsGCWCGSAFlAwQBFjALBglghkgBZQMEAQIwCgYIKoZIhvcNAwcw
DgYIKoZIhvcNAwICAgCAMA0GCCqGSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3
DQMCAgEoMA0GCSqGSIb3DQEBAQUABIGAPtBBdMSO3BpYtseJKrl8iFmfYvWsTOHo
nq+q/x0QHo1B4yXKZ22MJSht9OQpqKj0DA+UtWHilybwm90J9mUhqQO/2RTj4S7l
neFu7UZIIvLPtCB3efguE6ZNu0JqDUB3+QNmF9Q0rX8YX0A6j/YwMvuYRBCMLMYc
gwMuZ6VYZ8Y=

------CCC81977A319A32815270F41E73EFFD9--
```

**Comment by evstafiy** [comment]
Генерировал, с помощью ваших команд, однако результат сообщения отличается от вашего:

MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg="sha1"; boundary="----852012884FDF15DE554A38A07DA9130C"

This is an S/MIME signed message

------852012884FDF15DE554A38A07DA9130C

------852012884FDF15DE554A38A07DA9130C
Content-Type: application/pkcs7-signature; name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"

MIIF7QYJKoZIhvcNAQcCoIIF3jCCBdoCAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3
DQEHAaCCA20wggNpMIICUaADAgECAgQfI0RcMA0GCSqGSIb3DQEBCwUAMGUxCzAJ
BgNVBAYTAlJVMREwDwYDVQQIEwhLZW1lcm92bzERMA8GA1UEBxMIS2VtZXJvdm8x
DDAKBgNVBAoTA2FzazEUMBIGA1UECxMLYXNrLWdsb25hc3MxDDAKBgNVBAMTA2Fz
azAeFw0xNTEyMjgwMjMzNThaFw0yNTExMDUwMjMzNThaMGUxCzAJBgNVBAYTAlJV
MREwDwYDVQQIEwhLZW1lcm92bzERMA8GA1UEBxMIS2VtZXJvdm8xDDAKBgNVBAoT
A2FzazEUMBIGA1UECxMLYXNrLWdsb25hc3MxDDAKBgNVBAMTA2FzazCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAIJAjOW2hkGPHZQop2ffbPxCA8uvXsNR
o79ab1xpp6KeuEgNChh3mYy4JabOZF9PIBIDdCdyZzFKe3w/QacwFoJLI+PpvgpZ
Wg72O1J/5gXMnVBXcY2iLN+h4Qqn8665wNETgb9v5Xpw0oPdQj1nd9HMHH4C7mQ7
/16eLQl3gp1lixPnKPpNdtjpgb52MMGgksaC+lFjC1l9+flh7O2sS0WZzz6JkobX
etoSvD1WCRn811zFdHOqgwDFgV+stg0WttZFJANsWjDKbbtxalx7wST0r4ivLYAn
Ygr9JJkIXyKMF+WRRrOkSDSG7TmoPUFjmVXUe5YqrTy7J3NNURXEjUMCAwEAAaMh
MB8wHQYDVR0OBBYEFCh7HUw65K+wGSYsPNel7PWB2bkjMA0GCSqGSIb3DQEBCwUA
A4IBAQA5Z82OZJMooh3s3XBdMgy1ZKF/ckj7scF8By779RepXFrn1JuuDWs71Pz7
7I8y8E+4bHN5j5JPyCvjeZxihj5bQ5/WPksYpywG0X/qXiyTR0/gLEsWJSUXQ+sc
GqjzzcTNye9CvtItWjb3MZeq5mjeS6sjzhe5oyWpsMmvBIFRYuHTx3NXMKX0Q61U
V/NlH1HYDxkgUdmLgwvqovc9xResq3PLY7krqn7xGvG/3wmRXEMxf2tUoYKumbyb
lqVREg5M0ZveQx5cBK+3ZH0f3yfUU87tFMButKgXImcPyPxOluWl9M7bszoXiUF1
tENbp4BKy48yPMDlWVheRd0t88cMMYICSDCCAkQCAQEwbTBlMQswCQYDVQQGEwJS
VTERMA8GA1UECBMIS2VtZXJvdm8xETAPBgNVBAcTCEtlbWVyb3ZvMQwwCgYDVQQK
EwNhc2sxFDASBgNVBAsTC2Fzay1nbG9uYXNzMQwwCgYDVQQDEwNhc2sCBB8jRFww
CQYFKw4DAhoFAKCBsTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3
DQEJBTEPFw0xNTEyMjgwMjUxNDVaMCMGCSqGSIb3DQEJBDEWBBTaOaPuXmtLDTJV
v++VYBiQr9gHCTBSBgkqhkiG9w0BCQ8xRTBDMAoGCCqGSIb3DQMHMA4GCCqGSIb3
DQMCAgIAgDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDAN
BgkqhkiG9w0BAQEFAASCAQAitza4VZxchOVtXPsYif+6vHJJONZdbSx7nrxBkLYs
bYO19/w+jLv+dBtxTAxI83TQTsWAuGt2Xzehsd+tUbVUJyKqvl3Jj/74uYxEQvyH
cd8t6qXbinBmN0Z+r0/lmKC6T5s0OGZ7+rjUbaV/HFZdiGrE3B7xWk0rJkbN+KNI
h9oBll4Or4I8W/bx6CEPDmGjW016ZxDHzfuRq1m4xP3bm7XgHTJVilR//Sp+2ts+
hTkrDCTtgbCCFvBXYR7Qb+/VhuVguwBoYalygz5C0dbeuPaldk7VDVNf2f8r+HGd
l7A+myYqczZpHKbfWwrCv4JCNn/vbunLyaWjrX0jeCwR

------852012884FDF15DE554A38A07DA9130C--

**Comment by fr05t1k** [comment]
У вас после первого
```
------852012884FDF15DE554A38A07DA9130C
```
нет самих параметров.

Посмотрите содержание файла по пути $messageFile и содержание сообщения $message. Возможно они пустые.

**Comment by evstafiy** [comment]
да я это заметил. Однако все проверил, в $message=http://esia.gosuslugi.ru/usr_inf2015.12.28 14:20:23 +0700AVRK1211195d06340-332f-c531-7926-fd52579171be

**Comment by fr05t1k** [comment]
А содержание файла $messageFile?

**Comment by evstafiy** [comment]
после строчки file_put_contents($messageFile, $message);
содержимое в $messageFile = http://esia.gosuslugi.ru/usr_inf2015.12.28 14:32:08 +0700AVRK1211195d06340-332f-c531-7926-fd52579171be

**Comment by evstafiy** [comment]
по сути дела метод практически не изменен, единсвенное небольшие поправки

private function signPKCS7($message)
    {
        $configPath = getcwd()."/config";

        $certContent = file_get_contents($configPath."/ceresia_v1.cer");
        $keyContent = file_get_contents($configPath."/keyesia_v1.key");

        $cert = openssl_x509_read($certContent);
        if ($cert === false) {
            throw new Exception('Can\'t read a certificate');
        }

        $privateKey = openssl_pkey_get_private($keyContent, 'askesia');
        if ($privateKey === false) {
            throw new Exception('Can\'t read a private key');
        }

        // random unique directories for sign
        $messageFile = $configPath . DIRECTORY_SEPARATOR . uniqid();
        $signFile = $configPath . DIRECTORY_SEPARATOR . uniqid();
        file_put_contents($messageFile, $message);

        $signResult = openssl_pkcs7_sign(
            $messageFile,
            $signFile,
            $cert,
            $privateKey, []);

        if (!$signResult) {
            throw new Exception('ESIA : Sign fail');
        }

        $signed = file_get_contents($signFile);

        # split by section
        $signed = explode("\n\n", $signed);
        # get third section which contains sign and join into one line
        $sign = str_replace("\n", "", $this->urlSafe($signed[3]));

        unlink($signFile);
        unlink($messageFile);
        return $sign;
    }

**Comment by fr05t1k** [comment]
Можно попробовать сделать openssl_pkcs7_decrypt, но мне кажется дело все же в сообщении

**Comment by evstafiy** [comment]
$message = $this->getScope() . $this->timestamp . $this->getConfig()['client_id'] . $this->getState();
$this->clientSecret = $this->signPKCS7($message);
я уже все переправерил((

**Comment by evstafiy** [comment]
так с телом я разобрался, только теперь другое непонятно
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg="sha1"; boundary="----EA82554AC11213ACB8EF7EF8547582AB"

micalg="sha1", а надо micalg="sha256", сертификат сделал по вашим командам, в совтаве серта алгоритм sha256, все как надо. Не знаете с чем это связано и критично ли это?

**Comment by fr05t1k** [comment]
Вам выдали тестовые доступы? Там проверьте.
