### ISSUE TITLE
getToken

### ISSUE THREAD

**Issue by bash1981** [fr05t1k/esia#10]
после строки  $result = curl_exec($curl);
пустой $result, при том что запрос вроде полноценный (ниже представлен)
не подскажете, что может быть? 
https://esia-portal1.test.gosuslugi.ru/aas/oauth2/te?client_id=GATI001&code=eyJhbGciOiJSUzI1NiIsInNidCI6ImF1dGhvcml6YXRpb25fY29kZSIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJhdXRoX3RpbWUiOjE0OTk3Nzk0NDQ4NDIsImF1dGhfbXRoZCI6IlBXRCIsImV4cCI6MTUwMTI3OTI4NDYxNiwic2NvcGUiOiJmdWxsbmFtZT9vaWQ9MTAwMDI5OTY1NSBzbmlscz9vaWQ9MTAwMDI5OTY1NSIsImlzcyI6Imh0dHA6XC9cL2VzaWEuZ29zdXNsdWdpLnJ1XC8iLCJuYmYiOjE0OTk3Nzk0NDUsInVybjplc2lhOmNsaWVudDpzdGF0ZSI6IjZkMzVlOWE1LWE4YTQtNDhhNS1hYTQzLTI5M2MwNDc1MDdlOSIsInVybjplc2lhOnNpZCI6IjI1NmFiMDljNTRmNjEwZjc4NTNmN2VhNWM5MzEyNDZmMzUzMzM0MzU2YTk3OTM0OWYxZWJlNmZhYzk2ZWFlZmQiLCJwYXJhbXMiOnt9LCJ1cm46ZXNpYTpzYmoiOnsidXJuOmVzaWE6c2JqOmVpZCI6NzQxNDU2MywidXJuOmVzaWE6c2JqOm5hbSI6Ik9JRC4xMDAwMjk5NjU1IiwidXJuOmVzaWE6c2JqOm9pZCI6MTAwMDI5OTY1NSwidXJuOmVzaWE6c2JqOnR5cCI6IlAiLCJ1cm46ZXNpYTpzYmo6aXNfdHJ1Ijp0cnVlfSwiY2xpZW50X2lkIjoiR0FUSTAwMSIsImlhdCI6MTQ5OTc3OTQ0NX0.Osh3u90bwPuN_zCXDQjRTdpqIYeG_-j2hvjc2MLaxlhESOgJWUt9HygoiYaRyi6ND0GbO0rn7L_MYvmshTlLnyywoAjL6k1h5lU0siVwOVhZsFMFFIV2dYZJVD3m1-8RgA3WzeXXW08DdeFuRDVCGFBaXvBojaVSokQx-a43zfvFse9p7aF4ESH5uRvOlXz4rX4pz_S7GwXGgQyvEUxUS2nLKEV4gvmnW9NJppv9E9xunuR72zOYHW3rIzPQQfeUJ5BVGC5HRw83cRMiqaNJg7zERlF89POVIAvX_5PWWk2OZv5mH5g0Dji6imQ6LMtp49QUuNW8_rS-q_MfwuOA-A&grant_type=authorization_code&client_secret=MIIF0gYJKoZIhvcNAQcCoIIFwzCCBb8CAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3DQEHAaCCA1swggNXMIICP6ADAgECAgQmjJ5-MA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlJVMQ0wCwYDVQQIEwRTLVBiMQ0wCwYDVQQHEwRTLVBiMQ0wCwYDVQQKEwRHQVRJMQ0wCwYDVQQLEwRHQVRJMREwDwYDVQQDEwhBSVMgR0FUSTAeFw0xNzAxMjcwODEyMzZaFw00NjA4MjMwODEyMzZaMFwxCzAJBgNVBAYTAlJVMQ0wCwYDVQQIEwRTLVBiMQ0wCwYDVQQHEwRTLVBiMQ0wCwYDVQQKEwRHQVRJMQ0wCwYDVQQLEwRHQVRJMREwDwYDVQQDEwhBSVMgR0FUSTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIfFHJHmzFKOZyjKh9NQOmh25GElafIBEjDyeeXiXbTR_M-yW5Bv8zEG7-Sg4SOPFGSxgKQXfMQFkKb51jCVa_NN-Y-6fW_65BqT5wKbSOM6Z78NSEbOVv4c_tRmt3vIDV76vJ44lvHoOIKSf-kokak9rcwcE9DNrMhPmIIDjnwJ7sCxSOu2x5iy1dCF4TYAJVJ7CRocYVBNfxs75n0WL7nfSBWOObSXsOD2TO-K7aW99JX3bpVUx7HxP7WEikCKXKRQ5ZmRxANQ76UeZKMKYjtwqCA_Z1T7pzGmhKCZHcPa-_veTqZariUCTU8zNTL5ngznfva9O3l5gYHbpDITKfsCAwEAAaMhMB8wHQYDVR0OBBYEFHE2F1QH7sCFJ_knFRhuDRHigcYjMA0GCSqGSIb3DQEBBQUAA4IBAQAmBQ04opj0YB34w6JrMspnDGm32uKmaLuCOwDFT__YgzZgs1Lr0r-Wl4F1Po3Osppg_ork5tNiP0DZtlbOT4N54U3cT7B5VyV5Q4mRVdD9KOPXKj3L15XVnH1egQxCfY3OGxlHyLYEDBxZfr8LPw239st2VF8BAowk9FWhYx7czEx_YgXDFMjZEWDTWKIOZqFbjeGtIosHV82rwLGQFwcNGq1pMKLF4CDxpaGmKHeD4VI9s6iWt10njhTUW_SobE1w0zIREereQLsMZRK321H02Ss5ZFTb_tzWsp1hzEQ3EugnyyPMe2rCVHUwVQp_pRe3W0AZhYW1xoUTE2HyLr3SMYICPzCCAjsCAQEwZDBcMQswCQYDVQQGEwJSVTENMAsGA1UECBMEUy1QYjENMAsGA1UEBxMEUy1QYjENMAsGA1UEChMER0FUSTENMAsGA1UECxMER0FUSTERMA8GA1UEAxMIQUlTIEdBVEkCBCaMnn4wCQYFKw4DAhoFAKCBsTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNzA3MTExNDA4MjhaMCMGCSqGSIb3DQEJBDEWBBQOrhXB2MhOu_tvyOVDq1JYHDnX6DBSBgkqhkiG9w0BCQ8xRTBDMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIAgDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDANBgkqhkiG9w0BAQEFAASCAQA6V_tqmTjam6efcaoCHjABfX5Rk2biEdbwtwIHchfSHIpOfarzWx0XnjTeE2FFgnu0l5va2TYqE_sXux_8B8jxj2xl33AZlEXznkiFFukujVHZ22DaGInVFy5T-bH1e7Rogx6d4DkV49P1C2f7sRctzGigvD4Wu4pTiApodwcJKItpEgRxIM6gzDkIAc0itPzSUCZqr3QXPWhkM_VNy_ipr17TB6u0XYQTo4COFMJDGUX--n9xceKD-xDszkuUD5wkii31BZgWzguAETQg5rD2wbcA512C-EnraitwIH0wCVyAA2ReVskWFzJl8IVWrExp3JP3_sjVnuK1D9hTUqAw&state=cba22643-fe8c-4901-9f69-79f5524dd1c4&redirect_uri=http%3A%2F%2F127.0.0.1%2Fesia%2Fresponse.php&scope=fullname+snils&timestamp=2017.07.11+18%3A08%3A28+%2B0400&token_type=Bearer&refresh_token=cba22643-fe8c-4901-9f69-79f5524dd1c411

**Comment by Dkalugin** [comment]
Проверяйте CURL. Вот [тут ](https://github.com/fr05t1k/esia/issues/8) у [bbllek](https://github.com/bbllek) была [проблема](https://github.com/fr05t1k/esia/issues/8#issuecomment-303685660), которую она, как пишет, решила скачиванием и установкой caextract

**Comment by Dkalugin** [comment]
И, кстати, в Вашем URL не верно (как показала моя практика) сформирован блок
`scope=fullname+snils`
должно быть 
`scope=fullname snils`
У меня тестовый портал в качестве разделителя скоупов принял только пробел.

**Comment by bash1981** [comment]
Отлично! все помогло. Дальше затык с $result = json_decode($result);
до джейсона $result валидный, после - пусто.. будем копаться.. Спасибо за ответ!

**Comment by Dkalugin** [comment]
А с JSON у меня как раз проблема была аналогичная. Помогло "пинание" поддержки хостинга. И хотя поддержка твердо утверждала, что "мы ничего не делали, мы только проверили", после их "проверки" у меня все заработало.

**Comment by bash1981** [comment]
ээхх, знать бы что они "пнули" )) 
в моем случае все печальнее, я хостер )))

**Comment by Dkalugin** [comment]
Не сознаются )))
Проверяйте версию JSON. Проверяйте на "кошках" что JSON работает.

**Comment by bash1981** [comment]
только экспрессивные идиомы помогут мне выразить всю эту ситуацию..
оно заработало, само)) просто проверил ))))  нормальный класс возвращает.... 
теперь гляжу на затык с  getPersonInfo()..

**Comment by Dkalugin** [comment]
Да, у меня тоже многое после долгих плясок с бубнами начинало работать само и как надо ))
А что за затык с getPersonInfo()?

**Comment by bash1981** [comment]
у меня всего два скопа. фуллнайм и снилс
пытаюсь получить ...

        $url = $this->personUrl . '/' . $this->oid . '/snils';
        $request = $this->buildRequest();
        $result = $request->call($url);

$result пустой.. теоретически, должен дать ?

**Comment by bash1981** [comment]
Есть! ))) 
Dkalugin, спасибо за участие!! буду дальше ковыряться ))

**Comment by Dkalugin** [comment]
Я на тестовой среде СНИЛС получить так и не смог - FORBIDEN и хоть ты тресни :(
так что получаю я вот так:
`... 'scope' => 'fullname id_doc', ...`
после авторизации
`$personinfo = $esia->getPersonInfo();`
и дальше
```
        $user = "";
        $user .= iconv($encoding, "windows-1251", $personinfo->{'lastName'})." "; // фамилиё
        $user .= iconv($encoding, "windows-1251", $personinfo->{'firstName'})." ";// имя
        $user .= iconv($encoding, "windows-1251", $personinfo->{'middleName'});   // отчество
        $user .= "; гражданство ";
        $user .= $personinfo->{'citizenship'};
```

**Comment by bash1981** [comment]
у меня выпало 
object(stdClass)#2 (11) {
  ["stateFacts"]=>
  array(1) {
    [0]=>
    string(10) "EntityRoot"
  }
  ["eTag"]=>
  string(40) "9A14C1C039B6158499BC620637B365CEC10B4793"
  ["firstName"]=>
  string(9) "Имя003"
  ["lastName"]=>
  string(17) "Фамилия003"
  ["trusted"]=>
  bool(true)
  ["snils"]=>
  string(14) "000-000-600 03"
  ["updatedOn"]=>
  int(1499335968)
  ["status"]=>
  string(10) "REGISTERED"
  ["verifying"]=>
  bool(false)
  ["rIdDoc"]=>
  int(40124)
  ["containsUpCfmCode"]=>
  bool(false)
}

ну из этого выдерну что надо.. 
кстати, вопрос, как у Вас реализовано "разлогиниться"?

**Comment by Dkalugin** [comment]
Хм... надо будет еще раз попробовать со СНИЛСом...

а с "разлогиниться" допиливал сам, по инструкции к порталу. Получилось так:
```
     /**
     * Return an url for loguot
     *
     *     <a href="<?=$esia->getLogoutUrl();?>">Logout</a>
     *
     * @return string
     */
    public function getLogoutUrl()
    {
        $params = [
            'client_id' => $this->clientId,
            'redirect_uri' => $this->redirectUrl
        ];
        $url = $this->getCodeLogout() . '?%s';
        $request = http_build_query($params);
        $this->url = sprintf($url, $request);
        return $this->url;
    }
```

**Comment by bash1981** [comment]
спасибо!
Вы мне очень помогли, я так психовал со вчерашнего дня, кушать не мог )))

**Comment by Dkalugin** [comment]
Это зря! :)
Война-войной, а обед - по расписанию! :)

**Comment by bash1981** [comment]
логаут выбрасывает на страницу авторизации ЕСИА...
redirect_url задан, совпадает в с настройками системы в ЕСИА.. один хрен мимо бъет..

**Comment by Dkalugin** [comment]
У меня такое было, когда в передаваемом redirect_url была опечатка и он на один пробел отличался от заданного в настройках системы на портале. А так - да, не знаю, нафига так было делать, но передаваемый redirect_url должен строго совпадать с заданным в настройках.

**Comment by bash1981** [comment]
Я правильно понимаю, что это те настройки, которые прописываются на Технологическом портале https://esia.gosuslugi.ru/console/tech/sys.xhtml ?

**Comment by Dkalugin** [comment]
На боевом не знаю, на тестовом, это вот тут: https://esia-portal1.test.gosuslugi.ru/console/tech/sys.xhtml?orgOid=1000298922 в Данных Инфосистемы поле "URL системы" должно совпадать с тем, что передается в redirectUrl

**Comment by bash1981** [comment]
Спасибо, туплю))) проверяю URL системы на боевом контуре, а ползаю на тестовом..
