### ISSUE TITLE
C подключением Вашей авторизации через ЕСИА к сайту (стрящемуся) на Yii Framework сможете помочь?

### ISSUE THREAD

**Issue by Dkalugin** [fr05t1k/esia#13]
Здравствуйте!
Строим новый личный кабинет, решили делать на Yii Framework.
Есть пример авторизации через соц.сети по OpenId и EAuth. И есть Ваша авторизация. Пытаюсь из Вашей авторизации на том примере сделать, и не хватает знаний и навыков...
Сможете помочь?

**Comment by fr05t1k** [comment]
Добрый день! К сожалению, сейчас нет времени. Попробуйте поискать фрилансеров.
