### ISSUE TITLE
Авторизация перестала работать

### ISSUE THREAD

**Issue by Dkalugin** [fr05t1k/esia#17]
Добрый день!
На тестовой среде авторизация стала выдавать ошибку `Trying to get property of non-object`
строка 171 скрипт `/vendor/fr05t1k/esia/src/OpenId.php`

Мой стек вызова:
```
...
$esia = new TrfOpenId($config);
            $code = $session->get('esia_code');

            $esia->getToken($code);
            if (!$esia) $this->redirect($esia->getUrl());
```
До if() уже не доходит.
Никак понять не могу - у меня что-то где-то поломалось или на ГосУслугах опять что-то в тихую поменяли ((
Авторизовываться пытаюсь с 1-м тестовым пользователем, по СНИЛС 000-000-600 01 и 4-м, по СНИЛС 000-000-600 04

Не могли бы Вы у себя проверить, все ли в порядке?

**Comment by fr05t1k** [comment]
Я уже года 3 не пользуюсь ЕСИА. Чтобы поддерживать библиотеку, нужны доступы к тестовой среде, которых у меня нет.

**Comment by Dkalugin** [comment]
Готов предоставить временный доступ к своему коду. 
Или, если Вам это не интересно, подскажите, - в какую сторону "копать".

**Comment by fr05t1k** [comment]
Скиньте на почту доступы spavlovichev@gmail.com
```

**Comment by Dkalugin** [comment]
Написал

**Comment by fr05t1k** [comment]
https://gist.github.com/fr05t1k/77566730e5b09d5547663d0d8f4622b6

Вот рабочий пример по вашим данным
