### ISSUE TITLE
Быстрый запуск , первые шаги

### ISSUE THREAD

**Issue by ibobby1** [fr05t1k/esia#18]

**Comment by fr05t1k** [comment]
И не должно 😄

**Comment by ibobby1** [comment]
можешь помочь запустить ,а то не получается ,
Создал страничку с ссылкой , её куда положить нужно и на какие файлы ссылаться чтоб запустилось 
у меня пишет Fatal error: Class 'esia\OpenId' not found in C:\OSPanel\domains\komtt\esia\index.php on line 12
Но по факту он есть

**Comment by fr05t1k** [comment]
Начни с изучения php, потом почитай что такое composer. Если останутся вопросы, задавай.

**Comment by ibobby1** [comment]
Так с этим разобрался , из папки тест/дата взял сертификаты , подключил, при вызове пишет ошибку то что не может прочитать ключ 
 Uncaught exception 'esia\exceptions\SignFailException' with message 'Can't read a private key' 
Вопрос на ключ ставить нужно какие то права на чтение или выполнение ? или этот ключ можно где то получить чтоб он был валидным ?

**Comment by fr05t1k** [comment]
Этот ключ нужно генерировать и нести в Минком связи чтобы зарегистрировали вашу организацию с этим ключем. Подробностей я не знаю.

**Comment by ibobby1** [comment]
Спасибо , сейчас почитаю , посмотрю , отпишусь сюда как получится

**Comment by ibobby1** [comment]
Как и обещал 
Предварительные условия
Для работы требуется наличие публичного и приватного ключа в соответствии с методическими рекомендациями по работе с ЕСИА. Допускается использование самоподписного сертифката, который можно сгенерировать следующей командой:

openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -sha1 -keyout my_private.key -out my_public_cert.crt
Полученный в результате файл my_public_cert.crt должен быть привязан к информационной системе вашей организации на сайте Госуслуг, а также направлен вместе с заявкой на доступ к ЕСИА (подробнее см. документы http://minsvyaz.ru/ru/documents/?words=ЕСИА).

Для валидации ответов от ЕСИА потребуется публичный ключ, который можно запросить в технической поддержке ЕСИА, уже после регистрации информационной системы и получения доступа к тестовой среде ЕСИА. Валидация опциональна.
