### ISSUE TITLE
Верификация маркера доступа (токена)

### ISSUE THREAD

**Issue by Mats666** [fr05t1k/esia#21]
Доброго времени суток. Я в качестве примера смотрел проект, реализованный на php и использующий вашу библиотеку для взаимодействия с ЕСИА. Там не было проверки токена, который приходит из ЕСИА в обмен на код авторизации. Покопавшись в самих исходниках библиотеки я не нашёл функции проверки. В методических рекомендациях говорится о такой проверке и как она происходит, ссылаясь на документы и на то, как это должно быть реализовано с точки зрения шифрования. Можете обосновать эту ситуацию?

**Comment by fr05t1k** [comment]
Добрый день! Не могу точно сказать, библиотека писалась 3 года назад. Вы можете добавить эту функциональность.

**Comment by Mats666** [comment]
Ладно, очень жаль, что не можете ответить. Можно закрыть вопрос Issue.
