### ISSUE TITLE
Генерация ключевого контейнера и сертификата ключа

### ISSUE THREAD

**Issue by i--storm** [fr05t1k/esia#6]
Добрый день, Стас.
Столкнулся с внедрением интеграции авторизации через ЕСИА, но не могу найти как сгенерировать ключ через keytool. Вариантов запуска в сети просто море. Какой нужен для ЕСИА непонятно. В документации тоже только общие слова.
Подскажите пожалуйста командную строку для генерации

**Comment by fr05t1k** [comment]
@i--storm Добрый день. 

Я писал здесь:
https://github.com/fr05t1k/esia/issues/4#issuecomment-263773990

**Comment by Tavda** [comment]
openssl req -x509 -days 10000 -newkey rsa:2048 -keyout self.key -out self.pem
Я генерировал так. *.pem отправляем вместе с заявкой, *.key держим в секрете.  Выполнить можно на Linux/BSD сервере.

**Comment by AlexanderMatveev** [comment]
Самостоятельно сгенерирванные сертификаты дают ошибку `GCAErrorEnum.certificateInvalid`
