### ISSUE TITLE
Функция uniqid() возвращает не уникальные значения

### ISSUE THREAD

**Issue by i--storm** [fr05t1k/esia#7]
Файл OpenId.php
Строки 216, 217

$messageFile = $this->tmpPath . DIRECTORY_SEPARATOR . uniqid();
$signFile = $this->tmpPath . DIRECTORY_SEPARATOR . uniqid();

У меня на php 5.6 функция uniqid() возвращает одинаковые значения для обоих вызовов.
Это вызывает ошибку в строке 245
unlink($messageFile);
т.к. файл с таким именем уже удален предыдущей командой.

Если идти пошагово дебаггером, значения возвращаемые uniqid() отличаются.
Видимо при работе без дебаггера не успевает поменяться системное время.
Надо или добавить паузу между вызовами, или использовать другой генератор стучайных строк

**Comment by fr05t1k** [comment]
Можешь добавить `uniqid(rand())` и проверку на наличие файла.
