### ISSUE TITLE
getToken "валится" без ошибки

### ISSUE THREAD

**Issue by Dkalugin** [fr05t1k/esia#8]
Добрый день!
Пытаюсь подключить сайт к авторизации. Формирование ссылки, авторизация и возврат получились (правда, пришлось чуть-чуть поменять код). Дальше пытаюсь получить данные, не получается. PHP-скрипт буквально останавливается на вызове (определил "методом тыка эхом")
`$esia->getToken($_GET['code']);`
А конкретно, в getToken() на вызове
`$result = json_decode($result);`
Никаких ошибок не возвращается, в логи веб-сервера (access log / error log) тоже ничего не попадает...
Подскажите, пожалуйста, в какую сторону "копать"?

**Comment by fr05t1k** [comment]
Посмотри что вернулось на этой строке

**Comment by Dkalugin** [comment]
`var_dump(curl_exec($curl)); `возвращает следующее:

> string(908) "{"state":"b1f54dd3-bd4e-482f-bfb3-54c549fc5855","token_type":"Bearer","expires_in":3600,"refresh_token":"f831eae5-cfa6-4ce4-8675-30cd89015e2b","access_token":"eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ4NTYyMjksInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0ODUyNjI5LCJ1cm46ZXNpYTpzaWQiOiIzNjkwNDFkYzQ5MGVjMWIyNmMxYjQ2NjFlODM3YmU2NjNlNjAxMjllZTMzNzZlMmFiOTNjZjI1MDBkNTJhYmFhIiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ4NTI2Mjl9.naMlBqZ7yq_dsZb7hwF3Pmt5U3FjgfmYDSAVDzVtUfPy9QuiOextTr_aLbtgAQykInUg_6g8cZ7ymWTObhIw8bQlXx8VpiDRgjbEdD8XX9-fCiEipM720AlQn-GxcLjGd6Joojqc0yqRTXCg99FgWfEt7816t0lrQSfXQs6dGoxBtiKk4-E9pTeSOlsh-AWZERlC8Bm41LQW1EO30cbJSYu_joZYSCDR1G6hOJG_utEzxyW6AFIA0BvutxgFXCYp8IeB8H5oGKV0RK0lmo7WqqxRD2Q8fopK3rduLupWWIXCbCyzq234jXL0E5tObui306wI4i2d7n92AJygZW2yFQ"}"

а вот `var_dump(json_decode($curl));` выводит NULL и на этом все заканчивается...

**Comment by fr05t1k** [comment]
У вас валидный json. Но почему-то json_decode не хочет ваш json декодить. Нужно копать в эту сторону.

**Comment by Dkalugin** [comment]
Да, это я понял, спасибо. А что именно посмотреть, не подскажете? Какие-то настройки, переменные окружения, еще что-то? К сожалению, моего опыта и знаний не хватает - не сталкивался с JSON до сих пор и не представляю, что где и откуда...

**Comment by fr05t1k** [comment]
Тут можно узнать последние ошибки при кодировании/декодировании
http://php.net/manual/ru/function.json-last-error-msg.php
http://php.net/manual/ru/function.json-last-error.php

**Comment by Dkalugin** [comment]
Какая-то очень странная картинка у меня получается...
Вот кусок кода:
```
        $result = curl_exec($curl);
echo "<pre>";
var_dump(json_decode($result, true)); echo "<br>"; <== вот эта строчка выполняется последняя. после нее - пустота на выводе... Но данные вардамп отображает при этом!
var_dump(json_last_error()." &rarr; ".json_last_error_msg()); echo "<br>";
        $result = json_decode($result);
var_dump(json_last_error()." &rarr; ".json_last_error_msg()); echo "<br>";
echo "</pre>";
```

**Comment by fr05t1k** [comment]
У вас картина действительно странная. Просто посмотрите на результат (просто поместите скопированный ответ от сервера):

```
var_dump(json_decode('{"state" ... FQ"}', true));
var_dump(json_last_error());
var_dump(json_last_error_msg());
```

**Comment by Dkalugin** [comment]
код:
```
echo "<pre>";
var_dump(json_decode('{"state" ... FQ"}', true));
var_dump(json_last_error());
var_dump(json_last_error_msg());
echo "\n---------------------------------";
```
результат:

> <pre>NULL
> int(4)
> 

и все... Явно что-то "не ладно в королевстве Датском". Может, какая-нибудь версия JSON не та?
На тестовом сервере отработало вот так:

> <pre>NULL
> int(4)
> string(43) "object property name separator ':' expected"
> 
> ---------------------------------</pre>
Буду "копать" настройки.
Спасибо за подсказки!

**Comment by fr05t1k** [comment]
`{"state" ... FQ"}` я сократил для налядности, вставьте туда реальный ответ от сервера.

**Comment by Dkalugin** [comment]
Реальный ответ я вчера подставлял. Та же картинка была. И на "боевом" и на "тестовом".

**Comment by Dkalugin** [comment]
Хотя, не совсем... 
При подстановке реальной JSON строки в Ваш код на боевом сервере отработало вот так:

> <pre>array(5) {
>   ["state"]=>
>   string(36) "020b2aad-daef-4eb2-9d68-635df6303b4b"
>   ["token_type"]=>
>   string(6) "Bearer"
>   ["expires_in"]=>
>   int(3600)
>   ["refresh_token"]=>
>   string(36) "5f16c81b-2acb-4c01-adc8-3cfa51ae4c60"
>   ["access_token"]=>
>   string(747) "eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ5NDA0NjIsInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0OTM2ODYyLCJ1cm46ZXNpYTpzaWQiOiI5MDQ2ZTQ3Y2NlODUzMjkyZDZlZTAwMGVlMWViY2FlOGI4YTJmMTAwMjg5YzM2ZDYyZmZjOWU1MGU5MzI0Y2M2IiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ5MzY4NjJ9.yhi0KoHCfb6Xy6eopDsLpnRE_NeM-kOKoCatpB-oWVYxz_OcLcmbsgGkBLKLK6V4hbDzD--QmjsbpbKFNrHhSpG-GghUNcmCJ3Bd4vtqzdrDNNusZP2pjqOJdjQZ66_lEpnz1FmBSCTjy0-z067CNwRnenBOcqMjZOCZ15fUPpXppx-iJgrLV5zf7lnChG1M-QuxiJmNUjPggKwMFnjH0SS9gE6TpfgWyCfCAnSKQQANLAp4RYCmRtuuwRrbj9NQK1rP1uAlD_KQV9iPCQ4RjDSxJlqY6Y4G-dMVlVrHyLlCi65dBxT4apBIGiXoy1x6t0Mew8FJ8dJHHxB4Pwp2vQ"
> }
> int(0)

а на тестовом так:

> array(5) {
>   ["state"]=>
>   string(36) "020b2aad-daef-4eb2-9d68-635df6303b4b"
>   ["token_type"]=>
>   string(6) "Bearer"
>   ["expires_in"]=>
>   int(3600)
>   ["refresh_token"]=>
>   string(36) "5f16c81b-2acb-4c01-adc8-3cfa51ae4c60"
>   ["access_token"]=>
>   string(747) "eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ5NDA0NjIsInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0OTM2ODYyLCJ1cm46ZXNpYTpzaWQiOiI5MDQ2ZTQ3Y2NlODUzMjkyZDZlZTAwMGVlMWViY2FlOGI4YTJmMTAwMjg5YzM2ZDYyZmZjOWU1MGU5MzI0Y2M2IiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ5MzY4NjJ9.yhi0KoHCfb6Xy6eopDsLpnRE_NeM-kOKoCatpB-oWVYxz_OcLcmbsgGkBLKLK6V4hbDzD--QmjsbpbKFNrHhSpG-GghUNcmCJ3Bd4vtqzdrDNNusZP2pjqOJdjQZ66_lEpnz1FmBSCTjy0-z067CNwRnenBOcqMjZOCZ15fUPpXppx-iJgrLV5zf7lnChG1M-QuxiJmNUjPggKwMFnjH0SS9gE6TpfgWyCfCAnSKQQANLAp4RYCmRtuuwRrbj9NQK1rP1uAlD_KQV9iPCQ4RjDSxJlqY6Y4G-dMVlVrHyLlCi65dBxT4apBIGiXoy1x6t0Mew8FJ8dJHHxB4Pwp2vQ"
> }
> int(0)
> string(8) "No error"
> 
> ---------------------------------

**Comment by fr05t1k** [comment]
т.е. вы хотите сказать что скопировав строку и подставив в json_decode вы получаете валидные данные, а если напрямую то null? Такого не может быть. Значит в строках есть отличия.

**Comment by Dkalugin** [comment]
вот тестовый скрипт:
```
echo "<pre>";

$result = '{"state":"020b2aad-daef-4eb2-9d68-635df6303b4b","token_type":"Bearer","expires_in":3600,"refresh_token":"5f16c81b-2acb-4c01-adc8-3cfa51ae4c60","access_token":"eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ5NDA0NjIsInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0OTM2ODYyLCJ1cm46ZXNpYTpzaWQiOiI5MDQ2ZTQ3Y2NlODUzMjkyZDZlZTAwMGVlMWViY2FlOGI4YTJmMTAwMjg5YzM2ZDYyZmZjOWU1MGU5MzI0Y2M2IiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ5MzY4NjJ9.yhi0KoHCfb6Xy6eopDsLpnRE_NeM-kOKoCatpB-oWVYxz_OcLcmbsgGkBLKLK6V4hbDzD--QmjsbpbKFNrHhSpG-GghUNcmCJ3Bd4vtqzdrDNNusZP2pjqOJdjQZ66_lEpnz1FmBSCTjy0-z067CNwRnenBOcqMjZOCZ15fUPpXppx-iJgrLV5zf7lnChG1M-QuxiJmNUjPggKwMFnjH0SS9gE6TpfgWyCfCAnSKQQANLAp4RYCmRtuuwRrbj9NQK1rP1uAlD_KQV9iPCQ4RjDSxJlqY6Y4G-dMVlVrHyLlCi65dBxT4apBIGiXoy1x6t0Mew8FJ8dJHHxB4Pwp2vQ"}';
var_dump(json_decode($result, true));
var_dump(json_last_error());
var_dump(json_last_error_msg());

echo "\n---------------------------------";

$result = json_decode($result);
var_dump($result);
var_dump(json_last_error());
var_dump(json_last_error_msg());

echo "</pre>";
```

вот, что отрабатывает на боевом сервере:

> <pre>array(5) {
>   ["state"]=>
>   string(36) "020b2aad-daef-4eb2-9d68-635df6303b4b"
>   ["token_type"]=>
>   string(6) "Bearer"
>   ["expires_in"]=>
>   int(3600)
>   ["refresh_token"]=>
>   string(36) "5f16c81b-2acb-4c01-adc8-3cfa51ae4c60"
>   ["access_token"]=>
>   string(747) "eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ5NDA0NjIsInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0OTM2ODYyLCJ1cm46ZXNpYTpzaWQiOiI5MDQ2ZTQ3Y2NlODUzMjkyZDZlZTAwMGVlMWViY2FlOGI4YTJmMTAwMjg5YzM2ZDYyZmZjOWU1MGU5MzI0Y2M2IiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ5MzY4NjJ9.yhi0KoHCfb6Xy6eopDsLpnRE_NeM-kOKoCatpB-oWVYxz_OcLcmbsgGkBLKLK6V4hbDzD--QmjsbpbKFNrHhSpG-GghUNcmCJ3Bd4vtqzdrDNNusZP2pjqOJdjQZ66_lEpnz1FmBSCTjy0-z067CNwRnenBOcqMjZOCZ15fUPpXppx-iJgrLV5zf7lnChG1M-QuxiJmNUjPggKwMFnjH0SS9gE6TpfgWyCfCAnSKQQANLAp4RYCmRtuuwRrbj9NQK1rP1uAlD_KQV9iPCQ4RjDSxJlqY6Y4G-dMVlVrHyLlCi65dBxT4apBIGiXoy1x6t0Mew8FJ8dJHHxB4Pwp2vQ"
> }
> int(0)
> 

а вот, что на тестовом:

> <pre>array(5) {
>   ["state"]=>
>   string(36) "020b2aad-daef-4eb2-9d68-635df6303b4b"
>   ["token_type"]=>
>   string(6) "Bearer"
>   ["expires_in"]=>
>   int(3600)
>   ["refresh_token"]=>
>   string(36) "5f16c81b-2acb-4c01-adc8-3cfa51ae4c60"
>   ["access_token"]=>
>   string(747) "eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ5NDA0NjIsInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0OTM2ODYyLCJ1cm46ZXNpYTpzaWQiOiI5MDQ2ZTQ3Y2NlODUzMjkyZDZlZTAwMGVlMWViY2FlOGI4YTJmMTAwMjg5YzM2ZDYyZmZjOWU1MGU5MzI0Y2M2IiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ5MzY4NjJ9.yhi0KoHCfb6Xy6eopDsLpnRE_NeM-kOKoCatpB-oWVYxz_OcLcmbsgGkBLKLK6V4hbDzD--QmjsbpbKFNrHhSpG-GghUNcmCJ3Bd4vtqzdrDNNusZP2pjqOJdjQZ66_lEpnz1FmBSCTjy0-z067CNwRnenBOcqMjZOCZ15fUPpXppx-iJgrLV5zf7lnChG1M-QuxiJmNUjPggKwMFnjH0SS9gE6TpfgWyCfCAnSKQQANLAp4RYCmRtuuwRrbj9NQK1rP1uAlD_KQV9iPCQ4RjDSxJlqY6Y4G-dMVlVrHyLlCi65dBxT4apBIGiXoy1x6t0Mew8FJ8dJHHxB4Pwp2vQ"
> }
> int(0)
> string(8) "No error"
> 
> ---------------------------------object(stdClass)#1 (5) {
>   ["state"]=>
>   string(36) "020b2aad-daef-4eb2-9d68-635df6303b4b"
>   ["token_type"]=>
>   string(6) "Bearer"
>   ["expires_in"]=>
>   int(3600)
>   ["refresh_token"]=>
>   string(36) "5f16c81b-2acb-4c01-adc8-3cfa51ae4c60"
>   ["access_token"]=>
>   string(747) "eyJhbGciOiJSUzI1NiIsInNidCI6ImFjY2VzcyIsInR5cCI6IkpXVCIsInZlciI6MX0.eyJleHAiOjE0OTQ5NDA0NjIsInNjb3BlIjoiZnVsbG5hbWU_b2lkPTEwMDAyOTk2ODEiLCJpc3MiOiJodHRwOlwvXC9lc2lhLmdvc3VzbHVnaS5ydVwvIiwibmJmIjoxNDk0OTM2ODYyLCJ1cm46ZXNpYTpzaWQiOiI5MDQ2ZTQ3Y2NlODUzMjkyZDZlZTAwMGVlMWViY2FlOGI4YTJmMTAwMjg5YzM2ZDYyZmZjOWU1MGU5MzI0Y2M2IiwidXJuOmVzaWE6c2JqX2lkIjoxMDAwMjk5NjgxLCJjbGllbnRfaWQiOiJUUE0iLCJpYXQiOjE0OTQ5MzY4NjJ9.yhi0KoHCfb6Xy6eopDsLpnRE_NeM-kOKoCatpB-oWVYxz_OcLcmbsgGkBLKLK6V4hbDzD--QmjsbpbKFNrHhSpG-GghUNcmCJ3Bd4vtqzdrDNNusZP2pjqOJdjQZ66_lEpnz1FmBSCTjy0-z067CNwRnenBOcqMjZOCZ15fUPpXppx-iJgrLV5zf7lnChG1M-QuxiJmNUjPggKwMFnjH0SS9gE6TpfgWyCfCAnSKQQANLAp4RYCmRtuuwRrbj9NQK1rP1uAlD_KQV9iPCQ4RjDSxJlqY6Y4G-dMVlVrHyLlCi65dBxT4apBIGiXoy1x6t0Mew8FJ8dJHHxB4Pwp2vQ"
> }
> int(0)
> string(8) "No error"
> </pre>

**Comment by bbllek** [comment]
У меня аналогичная ошибка, а сервер у Вас случайно не IIS?

**Comment by Dkalugin** [comment]
Нет, Апач. С ошибкой я уже дальше продвинулся. JSON, вроде бы, заработал, удалось авторизоваться и получить токен. Дальше пытаюсь сделать getPersonInfo() и снова-здорова: общий стоп без объяснений. Колупаю потихоньку.

**Comment by fr05t1k** [comment]
@Dkalugin в чем было дело?

**Comment by Dkalugin** [comment]
А вот сие науке осталось не известным. Просил поддержку хостинга посмотреть, в чем дело. Они сказали, что все работает. И после этого все заработало. Спрашиваю - что делали? Говорят - ничего, проверили, все работало само и так... :(

**Comment by fr05t1k** [comment]
`php -m | grep json` не пробовали?

**Comment by Dkalugin** [comment]
bash-4.2$ php -m | grep JSON
bash-4.2$
т.е. ничего не выдает

**Comment by fr05t1k** [comment]
@Dkalugin у вас все странно. Вы показываете в примерах что json_decode у вас отрабатывает. Последняя команда говорит что у вас не расширения json. Тут возможно несколько вариантов. Если вы используете php как модуль для apache, то убедитесь что json у вас включен (хотя странно что в примерах у вас отрабатывает). На счет "тишина", "пустота" и прочего, убедитесь что отображение ошибок ключено, посмотрите логи. Просто "пустоты и тишины" быть не может в критических ситуациях.

P.S. Я просил написать `php -m | grep json`, а не `php -m | grep JSON`

**Comment by Dkalugin** [comment]
прошу прощения, с регистром мой косяк... в нижнем регистре вот:
-bash-4.2$ php -m | grep json
json
-bash-4.2$


php как модуль apache, да. json включен (это видно из phpinfo() ). Отображение ошибок включено. Продолжаю разбираться. Как будет очередной "затык" или разберусь, в чем дело - обязательно напишу.

**Comment by bbllek** [comment]
посмотрела ошибку 
   echo 'Ошибка curl: ' . curl_error($curl);
   exit();

   $result = json_decode($result);

SSL certificate problem: unable to get local issuer certificate

**Comment by bbllek** [comment]
проблема решилась тем что скачала https://curl.haxx.se/docs/caextract.html
и прописала в php.ini
curl.cainfo ="C:\путь\cacert.pem"
