### ISSUE TITLE
Сгененрированая подпись не проходит в ГосУслугах

### ISSUE THREAD

**Issue by kudis** [fr05t1k/esia#9]
Данная функция:
`$signResult = openssl_pkcs7_sign(
            $messageFile,
            $signFile,
            $cert,
            $privateKey,
            []
        );`
Кладёт в файл $signFile ключ, который не принимается ЕСИА (естественно я применял urlSafe() и выкладывал подпись в одну строку).
Возможно на момент написания Вашего скрипта, всё работало, но, видимо что-то изменилось с тех пор.
Перепробовал всяческие флаги данной функции, но ЕСИА упорно не хочет принимать подпись, выдавая OAuthErrorEnum.noGrants.
Есть ли у Вас рецепт от данной напасти?

**Comment by fr05t1k** [comment]
К сожалению, я уже больше года не пользуюсь ЕСИА.

**Comment by fr05t1k** [comment]
В этом тикете у ребят получилось получить токен и это было сравнительно не давно. https://github.com/fr05t1k/esia/issues/8

**Comment by Dkalugin** [comment]
Да, в этом месте у нас все отработало без проблем. Проверяйте конфиг - все ли правильно указали?

`$config = [
    'clientId' => 'код_системы_на_тестовом_портале',
    'redirectUrl' => 'URL_страницы_возврата',
    'portalUrl' => 'https://esia-portal1.test.gosuslugi.ru/',
    'privateKeyPath' => $esia_path.'путь_к_файлу_ключа.key',
    'privateKeyPassword' => '', // у нас сертификат самоподписанный, без шифрования, по этому здесь пусто
    'certPath' => $esia_path.'путь_к_файлу_сертификата.crt',
    'tmpPath' => $esia_path.'tmp/',
    'scope' => 'fullname id_doc' // скоупы, которые будут запрашиваться, разделенные пробелом (пробелами)
];`

**Comment by kudis** [comment]
Проблема оказалась действительно в scope. Использовал 'fullname id_doc openid' и всё заработало. Единственное, не могу получить адрес и контактные данные по адресам:
https://esia.gosuslugi.ru/rs/prns/{oid}/addrs и https://esia.gosuslugi.ru/rs/prns/{oid}/ctts у меня идут Forbidden.
Не знаете какой scope нужно ещё добавить, чтобы пускало?

**Comment by Dkalugin** [comment]
Нет, не в курсе. Как разберетесь - напишите здесь, пожалуйста. Мне, вероятно, тоже с этим еще предстоит разбираться.
